name: build kernel for imx6q
run-name: ${{ github.actor }} is building kernel for imx6q 🚀
on:
  repository_dispatch:
  workflow_dispatch:

env:
  UBOOT_BRANCH: 2022.10+fslc
  custom-uboot-configfile-path: imx6q/uboot.config
  kernel-branch: 6.6-2.1.x-imx
  custom-kernel-dtsfile-path: imx6q/imx6qdl-sabredsd.dtsi
  des-kernel-dtsfile-path: linux-fslc/arch/arm/boot/dts/nxp/imx/imx6qdl-sabredsd.dtsi

jobs:
  build-uboot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@main

      - name: clone uboot code
        run: | 
          echo ${UBOOT_BRANCH}
          git clone -b ${uboot-branch} https://github.com/Freescale/u-boot-fslc.git
          
      - name: install tools
        run: |
          docker rmi `docker images -q`
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo apt install make git gcc-arm-none-eabi gcc bison flex libssl-dev dpkg-dev lzop libncurses5-dev -y



      - name: uboot defconfig
        run: |
          cd u-boot-fslc
          make distclean
          make ARCH=arm CROSS_COMPILE=arm-none-eabi- mx6sabresd_defconfig

      - name: load custom config
        run: cp ${custom-uboot-configfile-path} u-boot-fslc/.config
      
      - name: build uboot
        run: |
          cd u-boot-fslc
          make -j$(nproc) ARCH=arm CROSS_COMPILE=arm-none-eabi-
          
      - name: display uboot size
        run: |
          cd u-boot-fslc
          ls -l u-boot*

      - name: install tools for building kernel
        run: sudo apt install make gcc-arm-linux-gnueabihf gcc bison flex libssl-dev dpkg-dev lzop vim -y

      - name: show current directory
        run: pwd
        
      - name: clone kernel code
        run: git clone -b ${kernel-branch} https://github.com/Freescale/linux-fslc.git

      - name: load custom dts file
        run: cp ${custom-kernel-dtsfile-path} ${des-kernel-dtsfile-path}

      - name: defconfig
        run: |
          cd linux-fslc
          make distclean
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- imx_v7_defconfig
          
      - name: build kernel
        run: |
          cd linux-fslc
          make -j$(nproc) ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-

      - name: build uImage
        run: |
          sudo cp u-boot-fslc/tools/mkimage /usr/bin
          cd linux-fslc
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- uImage LOADADDR=0x80008000

      - name: display kernel size
        run: |
          cd linux-fslc
          ls -l arch/arm/boot/
          ls -l arch/arm/boot/dts/nxp
            
      - name: Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: prebuild_driver
          body: imx6q's image of uboot(branch${uboot-branch}) and kernel(branch ${kernel-branch})
          files: |
            u-boot-fslc/u-boot-dtb.imx
            u-boot-fslc/u-boot.bin
            linux-fslc/arch/arm/boot/zImage
            linux-fslc/arch/arm/boot/uImage
