name: build kernel for imx6q
run-name: ${{ github.actor }} is building kernel for imx6q 🚀
on:
  repository_dispatch:
  workflow_dispatch:
jobs:
  build-uboot:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@main
        
      - name: install tools
        run: |
          sudo apt update
          sudo apt install make git gcc-arm-none-eabi gcc bison flex libssl-dev dpkg-dev lzop libncurses5-dev -y

      - name: clone uboot code
        run: | 
          git clone -b 2024.07+fslc https://github.com/Freescale/u-boot-fslc.git

      - name: build
        run: |
          cp uboot-config u-boot-fslc/.config
          cd u-boot-fslc
          echo -e "$(nproc) thread compile"
          make ARCH=arm CROSS_COMPILE=arm-none-eabi-

        
